"""daily_usage

Revision ID: 90f71e507d8e
Revises: 886a3412c76e
Create Date: 2026-06-08 22:21:49.259330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f71e507d8e'
down_revision: Union[str, Sequence[str], None] = '886a3412c76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'local_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_usage')
    # ### end Alembic commands ###
