"""quota_tier

Revision ID: d46eaae3dee4
Revises: 90f71e507d8e
Create Date: 2026-06-08 22:32:58.129980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46eaae3dee4'
down_revision: Union[str, Sequence[str], None] = '90f71e507d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_tier',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('clean_days', sa.Integer(), nullable=False),
    sa.Column('last_day', sa.String(length=10), nullable=True),
    sa.Column('notice', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quota_tier')
    # ### end Alembic commands ###
